Clear Comments Feature
mozilla/assay pull request #46
Opened 2024-05-27 16:59 UTC by chrstinalin

Fixes #25

**Changes**
- Manually deleting comments from context
![image](https://github.com/mozilla/assay/assets/44586776/287c5ece-47e6-482d-b4bf-e3ba7740a8a4)
- Setting to delete comments automatically on export. The first time the user exports, Assay will prompt for whether the user wants to delete the comments in the version after exporting. It will then ask the user if they would like to save their choice. On future exports, Assay will immediately delete, ignore, or ask to delete comments according to user preference. This preference can be changed again in settings.
![image](https://github.com/mozilla/assay/assets/44586776/22bbccd7-4b28-466c-995c-791ba7002f11)
![image](https://github.com/mozilla/assay/assets/44586776/47044568-95ad-43f9-ab79-d4653c0480f9)
![image](https://github.com/mozilla/assay/assets/44586776/9a536fc1-75d3-4be9-a84c-ba14fe8617c4)
- Fixed issue where exporting from context would export from the active text editor rather than whichever folder was selected.

**Known Issues**
- When a bulk delete occurs, file decorators are not updated unless the user individually clicks one each file. Similar behaviour occurs with other extensions/VS Code functionality that uses file decorators (ex. Git unsigned/modified/deleted decorators), so whether this is an issue that needs/can be addressed is unclear.

2024-06-03 14:26 UTC, dotproto requested changes
I think it's out of scope for this PR, but the main through-line on my comments in this review is that in the future I think we should adopt a more object-oriented approach to Assay's architecture. I mentioned in a previous review that I thought we should collect some related functionality in a CommentManager class. I see a couple other areas where can start to collect functionality into classes, namely Comment and CommentCollection. It might be best if we chat more about this over a call. 

The suggested changes to test descriptions are primarily for consistency with how existing tests are written. To be honest, I'd prefer to have all tests use a terminal period, but I don't want to roll that change into this PR. If you'd like to change the pattern to use terminal periods, feel free to reject my suggestions here and create a new PR that introduce terminal periods in the other tests.

2024-06-03 14:36 UTC, chrstinalin commented on src/commands/exportComments.ts
> +  vscode.workspace.applyEdit(edit);
I'm not sure, actually. This was pre-existing code I glossed over originally. It doesn't really make sense to me either (and I cant see it affecting the function), so I just removed it.

2024-06-03 15:20 UTC, chrstinalin commented on src/utils/commentManager.ts
> +  private *iterateByComment(comments: CommentsCache) {
I think refactoring Assay to be more object-oriented may be an issue in of itself. I'm finding the current folder structure less and less suitable, and I feel fully committing to OOP should come with refactoring the folders as well.

2024-06-03 22:08 UTC, dotproto approved these changes
LGTM. I shared a couple of thoughts, but none are blocking.

In the future I'd prefer to keep changes like the `.test.ts` terminal period changes in separate commits. Some notable disadvantages of rolling those changes into this PR rae that it increases the amount of code that needs to be reviewed in the PR, bloats the number of changes and scope of final merge commit, and makes it more difficult to understand what's actually changing in the commit when digging through version history or a `git blame`.

2024-06-03 22:08 UTC, dotproto commented on src/commands/exportComments.ts
> +  if (deleteCachedComments) {
Nit: If the variable isn't going to be used until later, it's best to move it's declaration closer to it's use location. This helps with readability as the reader doesn't have to hold as much state in mind while reading through the code. It also has the (generally very minor) benefit that an early return will not perform unnecessary work.
```suggestion
  const document = await vscode.workspace.openTextDocument({
    content: compiledComments,
    language: "text",
  });

  vscode.window.showTextDocument(document, vscode.ViewColumn.Beside);

  if (compiledComments) {
    vscode.env.clipboard.writeText(compiledComments);
    vscode.window.showInformationMessage("Comments copied to clipboard.");
  }

  const deleteCachedComments = await getDeleteCommentsPreference();
  if (deleteCachedComments) {
```

2024-06-04 12:33 UTC, chrstinalin commented on src/utils/getDeleteCommentsPreference.ts
> +    ["Save my Preference", "Ask Every Time"],
With code-manager, there's currently a hardcoded link in addons-server that directly links the English version of it. Though, now that I'm looking at it, seems more a [limitation](https://github.com/mozilla/addons-server/blob/8f08af88323bbb871b51dda42be39d4c1db0021f/src/olympia/reviewers/templatetags/code_manager.py#L10) than a requirement.

This feels like good practice to implement regardless, so I made the issue anyway.

2024-06-04 12:34 UTC, merged